// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4vI7LHJO28-y8kk--rHLIhLD7niv5w5Q',
    appId: '1:375156059088:web:10b31ed21f5e294625a7d5',
    messagingSenderId: '375156059088',
    projectId: 'flutter-firebase-ba21b',
    authDomain: 'flutter-firebase-ba21b.firebaseapp.com',
    storageBucket: 'flutter-firebase-ba21b.appspot.com',
    measurementId: 'G-H568T75JH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4yKAiixI6LyNJN71bYIDiACyL-oGefU',
    appId: '1:375156059088:android:0c91ea36d8ee31d525a7d5',
    messagingSenderId: '375156059088',
    projectId: 'flutter-firebase-ba21b',
    storageBucket: 'flutter-firebase-ba21b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcE-qOYh9SllgzgfiDAgL0RDrx5ba-fU',
    appId: '1:375156059088:ios:80470ed5ca87871225a7d5',
    messagingSenderId: '375156059088',
    projectId: 'flutter-firebase-ba21b',
    storageBucket: 'flutter-firebase-ba21b.appspot.com',
    iosBundleId: 'com.example.firebaseImpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcE-qOYh9SllgzgfiDAgL0RDrx5ba-fU',
    appId: '1:375156059088:ios:80470ed5ca87871225a7d5',
    messagingSenderId: '375156059088',
    projectId: 'flutter-firebase-ba21b',
    storageBucket: 'flutter-firebase-ba21b.appspot.com',
    iosBundleId: 'com.example.firebaseImpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4vI7LHJO28-y8kk--rHLIhLD7niv5w5Q',
    appId: '1:375156059088:web:f57df742a273da5525a7d5',
    messagingSenderId: '375156059088',
    projectId: 'flutter-firebase-ba21b',
    authDomain: 'flutter-firebase-ba21b.firebaseapp.com',
    storageBucket: 'flutter-firebase-ba21b.appspot.com',
    measurementId: 'G-QK221E9C8V',
  );
}
